services:
  traefik:
    image: traefik:v3.1
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`airgen.studio`) && PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.traefik.middlewares=production-auth@docker"
      - "traefik.http.middlewares.production-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS}"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  neo4j:
    image: neo4j:5.25
    environment:
      NEO4J_AUTH: "${GRAPH_USERNAME}/${GRAPH_PASSWORD}"
    volumes:
      - neo4jdata:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT}
      API_JWT_SECRET: ${API_JWT_SECRET}
      API_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
      REDIS_URL: "redis://redis:6379"
      WORKSPACE_ROOT: /workspace
      AI_DRAFT_LIMIT: ${AI_DRAFT_LIMIT:-5}
      AI_DRAFT_CACHE_TTL: ${AI_DRAFT_CACHE_TTL:-900}
      GRAPH_URL: bolt://neo4j:7687
      GRAPH_USERNAME: ${GRAPH_USERNAME}
      GRAPH_PASSWORD: ${GRAPH_PASSWORD}
      GRAPH_DATABASE: ${GRAPH_DATABASE:-neo4j}
      GRAPH_ENCRYPTED: ${GRAPH_ENCRYPTED:-false}
      LLM_PROVIDER: "${LLM_PROVIDER}"
      LLM_API_KEY: "${LLM_API_KEY}"
      OPENAI_API_KEY: "${LLM_API_KEY}"
      LLM_MODEL: "${LLM_MODEL:-gpt-4o-mini}"
      LLM_BASE_URL: "${LLM_BASE_URL}"
      LLM_TEMPERATURE: "${LLM_TEMPERATURE:-0.2}"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`airgen.studio`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=${API_PORT}"
      - "traefik.http.middlewares.api-strip.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-strip@docker"
    volumes:
      - ./workspace:/workspace
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`airgen.studio`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      # - "traefik.http.routers.frontend.middlewares=production-auth@docker"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  pgdata:
  neo4jdata:
