services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airgen}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airgen}
      POSTGRES_DB: ${POSTGRES_DB:-airgen}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

  neo4j:
    image: neo4j:5.25
    environment:
      NEO4J_AUTH: "${GRAPH_USERNAME:-neo4j}/${GRAPH_PASSWORD:-airgen-graph}"
    ports:
      - "${GRAPH_BOLT_PORT:-7687}:7687"
      - "${GRAPH_HTTP_PORT:-7474}:7474"
    volumes:
      - neo4jdata:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      API_HOST: ${API_HOST:-0.0.0.0}
      API_PORT: ${API_PORT:-8787}
      API_JWT_SECRET: ${API_JWT_SECRET:-change_me}
      API_ENV: ${API_ENV:-development}
      DATABASE_URL: "postgresql://${POSTGRES_USER:-airgen}:${POSTGRES_PASSWORD:-airgen}@postgres:5432/${POSTGRES_DB:-airgen}"
      REDIS_URL: "redis://redis:6379"
      WORKSPACE_ROOT: /workspace
      AI_DRAFT_LIMIT: ${AI_DRAFT_LIMIT:-5}
      AI_DRAFT_CACHE_TTL: ${AI_DRAFT_CACHE_TTL:-900}
      GRAPH_URL: bolt://neo4j:7687
      GRAPH_USERNAME: ${GRAPH_USERNAME:-neo4j}
      GRAPH_PASSWORD: ${GRAPH_PASSWORD:-airgen-graph}
      GRAPH_DATABASE: ${GRAPH_DATABASE:-neo4j}
      GRAPH_ENCRYPTED: ${GRAPH_ENCRYPTED:-false}
      LLM_PROVIDER: "${LLM_PROVIDER}"
      LLM_API_KEY: "${LLM_API_KEY}"
      OPENAI_API_KEY: "${LLM_API_KEY}"
      LLM_MODEL: "${LLM_MODEL:-gpt-4o-mini}"
      LLM_BASE_URL: "${LLM_BASE_URL}"
      LLM_TEMPERATURE: "${LLM_TEMPERATURE:-0.2}"
    ports:
      - "${API_PORT:-8787}:${API_PORT:-8787}"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      neo4j:
        condition: service_healthy
    volumes:
      - ./workspace:/workspace

volumes:
  pgdata:
  neo4jdata:
