-- Migration: Create SnapDraft tables
-- Description: Tables for storing SnapDraft technical drawing generation data

-- Main SnapDraft drawings table
CREATE TABLE IF NOT EXISTS snapdraft_drawings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  element_id UUID NOT NULL,
  element_type VARCHAR(50) NOT NULL CHECK (element_type IN ('block', 'interface')),
  user_id UUID NOT NULL,
  tenant_slug VARCHAR(255) NOT NULL,  -- Tenant slug (tenants are in Neo4j, not PostgreSQL)

  spec_json JSONB NOT NULL,
  style VARCHAR(50) NOT NULL CHECK (style IN ('engineering', 'architectural', 'schematic')),

  dxf_file_path TEXT,
  svg_file_path TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_snapdraft_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_snapdraft_element ON snapdraft_drawings(element_id, element_type);
CREATE INDEX IF NOT EXISTS idx_snapdraft_user ON snapdraft_drawings(user_id);
CREATE INDEX IF NOT EXISTS idx_snapdraft_tenant ON snapdraft_drawings(tenant_slug);
CREATE INDEX IF NOT EXISTS idx_snapdraft_created ON snapdraft_drawings(created_at DESC);

-- Generation logs table for debugging and cost tracking
CREATE TABLE IF NOT EXISTS snapdraft_generation_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  drawing_id UUID NOT NULL,
  llm_model VARCHAR(100),
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  latency_ms INTEGER,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_snapdraft_log_drawing FOREIGN KEY (drawing_id) REFERENCES snapdraft_drawings(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_snapdraft_logs_drawing ON snapdraft_generation_logs(drawing_id);
CREATE INDEX IF NOT EXISTS idx_snapdraft_logs_created ON snapdraft_generation_logs(created_at DESC);

-- Update trigger for updated_at
CREATE OR REPLACE FUNCTION update_snapdraft_drawings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_snapdraft_drawings_updated_at
BEFORE UPDATE ON snapdraft_drawings
FOR EACH ROW
EXECUTE FUNCTION update_snapdraft_drawings_updated_at();

-- Comments for documentation
COMMENT ON TABLE snapdraft_drawings IS 'Stores SnapDraft technical drawing generation results';
COMMENT ON COLUMN snapdraft_drawings.element_id IS 'ID of the architecture block or interface';
COMMENT ON COLUMN snapdraft_drawings.element_type IS 'Type of element: block or interface';
COMMENT ON COLUMN snapdraft_drawings.spec_json IS 'Complete drawing specification JSON generated by LLM';
COMMENT ON COLUMN snapdraft_drawings.style IS 'Drawing style: engineering, architectural, or schematic';
COMMENT ON COLUMN snapdraft_drawings.dxf_file_path IS 'Path to generated DXF file on disk';
COMMENT ON COLUMN snapdraft_drawings.svg_file_path IS 'Path to generated SVG preview file on disk';

COMMENT ON TABLE snapdraft_generation_logs IS 'Logs SnapDraft generation requests for debugging and cost tracking';
COMMENT ON COLUMN snapdraft_generation_logs.llm_model IS 'OpenAI model used (e.g., gpt-4o)';
COMMENT ON COLUMN snapdraft_generation_logs.prompt_tokens IS 'Number of tokens in the prompt';
COMMENT ON COLUMN snapdraft_generation_logs.completion_tokens IS 'Number of tokens in the completion';
COMMENT ON COLUMN snapdraft_generation_logs.latency_ms IS 'Total generation latency in milliseconds';
